artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/rafael-raiser/portfolio_clustering/gh-pages/star_classification.csv
  local_data_file: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


